#this script creates DEMs at first and second order in approximations for surface code SE with random H error models#
#the goal is to compare different approximations#
import os
os.environ['OPENBLAS_NUM_THREADS'] = '1' 
os.environ['GOTO_NUM_THREADS'] = '1' 
os.environ['OMP_NUM_THREADS'] = '1' 
os.environ['NUMEXPR_NUM_THREADS'] = '1' 
os.environ['VECLIB_MAXIMUM_THREADS'] = '1' 
os.environ['MKL_NUM_THREADS'] = '1' 

from mpi4py import MPI 
comm = MPI.COMM_WORLD
rank = comm.Get_rank()
size = comm.Get_size()

import numpy as np
import stim
import pygsti
import time
import itertools
import scipy as sp

import pickle

from collections import Counter

import pygsti.tools.errgenproptools as eprop
from pygsti.errorgenpropagation.errorpropagator import ErrorGeneratorPropagator
from matplotlib import pyplot as plt

from pygsti.extras.dem_construction import pygsti_object_builders as obj
from pygsti.extras.dem_construction import helper_functions as helper
from pygsti.extras.dem_construction import dem_tools as dems

import surface_code_setup as surface

from qiskit.primitives import StatevectorSampler
from qiskit_svs_tools import * 
from qiskit.quantum_info import Statevector

from tensor_contraction import compute_all_probs

d=3
rounds= 2 
erates = np.linspace(0.001,0.003, num=3)
erates = np.append(erates, np.linspace(0.002, 0.02, num=11))
num_models= 10 

def compute_outcome_distribution_from_dem(dem):
    """
    Compute the outcome distribution from a DEM using log and Hadamard transform.

    Parameters:
    - dem: a detector error model

    Returns: 
    - prob_estimate: array of 2^n probabilities, in increasing binary order
    """
    # Convert DEM to attenuations
    stim_dem_str = dems.format_dem_stim(dem, n_logical=0)
    stim_dem = stim.DetectorErrorModel(stim_dem_str)
    attenuations = np.zeros(2**stim_dem.num_detectors, dtype=float)
    all_bitstrings = np.array([[int(bit) for bit in format(n, f'0{stim_dem.num_detectors}b')]for n in range(2**stim_dem.num_detectors)])
    for event in stim_dem:
        prob = event.args_copy()[0]
        targets = [target.val for target in event.targets_copy()]
        event = [1 if (stim_dem.num_detectors-idx-1) in targets else 0 for idx in range(stim_dem.num_detectors)]    
        attenuation = -np.log(1-2*prob)
        attenuations += attenuation * (1-(-1)**np.dot(all_bitstrings, event))/2
    
    # Compute polarizations from attenuations
    polarizations = np.exp(-attenuations)
    polarizations[0] = 1

    # Compute probabilities from polarizations
    probabilities = sp.linalg.hadamard(2**stim_dem.num_detectors) @ polarizations / 2**stim_dem.num_detectors
    nds = stim_dem.num_detectors

    probs_dict = {str(bin(b)[2:]).zfill(nds)[::-1]:p for b,p in enumerate(probabilities)}
    return probs_dict

def compute_probs_from_dem(dem):
    '''
    generates samples from a detector error model
    dem (dict): A dictionary specifying the DEM
    n_shots (int): number of samples to take
    '''
    stim_dem_str = dems.format_dem_stim(dem, n_logical=0)
    stim_dem = stim.DetectorErrorModel(stim_dem_str)
    est_probs = compute_all_probs(stim_dem)
    
    return est_probs

def errorgens_to_unitary(edict, nq):
    #returns np array of the process matrix rep of the error generated by the generator in edict
    egen = pygsti.modelmembers.operations.lindbladerrorgen.LindbladErrorgen.from_elementary_errorgens(edict,state_space=pygsti.baseobjs.QubitSpace(nq))
    pm = pygsti.modelmembers.operations.ExpErrorgenOp(egen).to_dense()
    return pygsti.tools.optools.superop_to_unitary(pm)

if __name__=='__main__':
    for i in range(num_models):
        for erate in erates:
            error_rates_dict = {}
    
            def generate_random_sparse_h_rates(num_qs, num_rates, scale=0.01):
                #pick a random subset of the H errorgens
                nq_paulis = list(''.join(p) for p in itertools.product(['I','X','Y','Z'], repeat=num_qs))[1:]
                chosen_paulis = np.random.choice(nq_paulis, size=num_rates, replace=False)

                #pick random rates
                edict = {('H', p): np.random.normal(loc=0, scale=scale) for p in chosen_paulis}
                return edict
                
            error_rates_dict['Gh'] = generate_random_sparse_h_rates(num_qs=1, num_rates=3, scale=erate*0.2)
            error_rates_dict['Gcnot'] = generate_random_sparse_h_rates(num_qs=2, num_rates=3, scale=erate)
        
        
            theta, parameter_indexing = helper.build_parameter_vector(error_rates_dict)
        
            unitary_error_dict = {'Gh': errorgens_to_unitary(error_rates_dict['Gh'], nq=1),
                              'Gcnot': errorgens_to_unitary(error_rates_dict['Gcnot'], nq=2)}
        
        
            mr_pcircuit, mr_qubit_labels, mr_ancilla_qubits, data_qubits, ancilla_qubits, x_ancilla_qubits, z_ancilla_qubits, qubit_labels = surface.setup_surface_code(d, rounds)
            n_qubits = len(mr_qubit_labels)
            n_ancilla = len(mr_ancilla_qubits)
        
            mr_pcircuit = mr_pcircuit.serialize()
            mr_pspec = obj.create_processor_spec(mr_pcircuit, mr_qubit_labels)
            
            num_parameters = len(parameter_indexing)
            mr_model = obj.build_model(error_rates_dict, mr_pspec, oneQ_gate_names=['Gh'], twoQ_gate_names=['Gcnot'])
            mr_egp = ErrorGeneratorPropagator(mr_model)
            
            output_state_tableau, output_state_inverse_tableau = surface.compute_tableau_and_inverse_tableau(mr_pcircuit, mr_qubit_labels, mr_pspec, data_qubits, z_ancilla_qubits, x_ancilla_qubits, qubit_labels, ancilla_qubits)
        
            mapping_to_eoc_eeg = mr_egp.errorgen_transform_map(mr_pcircuit, include_spam=False)
            eeg_terms = list(set(mapping_to_eoc_eeg.values()))
    
            z_stabilizers, x_stabilizers = surface.compute_stabilizers_data(mr_pcircuit, mr_qubit_labels, mr_pspec, data_qubits, z_ancilla_qubits, x_ancilla_qubits, qubit_labels, ancilla_qubits)
            stabilizers_tableau = stim.Tableau.from_stabilizers([stim.PauliString(s) for s in z_stabilizers+x_stabilizers], allow_underconstrained=True)
            stabilizers=z_stabilizers+x_stabilizers
        
            n_qubits = len(mr_qubit_labels)
            
            anc_meas = [('Z',(q,)) for q in mr_ancilla_qubits] #ancilla measurements
            eoc_stabs = [(s, data_qubits) for s in stabilizers]#eoc_stabilizers 
            eoc_logical = [('Z'*d, tuple(2*i+1 for i in range(d)))]#eoc logical
            measurements = anc_meas + eoc_logical #+ eoc_stabs #list of tuples of the form (pauli, tuple_of_qubits) encoding the measurements in this circuit
            
            if rounds>1:
                final_check_qs = [len(qubit_labels)+(rounds-2)*len(ancilla_qubits)+ancilla_qubits.index(j) for j in z_ancilla_qubits]
            else:
                final_check_qs = z_ancilla_qubits
        
            n_stabs = len(z_stabilizers+x_stabilizers) 
            anc_detectors = [[i] for i in range(n_stabs)]
            for k in range(rounds-1):
                anc_detectors += [(i+(k*n_stabs), i+((k+1)*n_stabs)) for i in range(n_stabs)]
            
            detectors = anc_detectors+[[len(measurements)-1]] #+final_dets+[[len(measurements)-1]]
            dets_as_pauli_strings = [dems.get_detector_as_parity(d, measurements, n_qubits) for d in detectors]
        
        
            eoc_eeg = mr_egp.propagate_errorgens_bch(mr_pcircuit, bch_order=2, include_spam=False)
        
            sim = stim.TableauSimulator()
            sim.set_inverse_tableau(output_state_tableau**-1)
        
            eoc_eeg1 = mr_egp.propagate_errorgens_bch(mr_pcircuit, bch_order=1, include_spam=False)
            dem_logical =  dems.generate_dem_higher_order(dets_as_pauli_strings, eoc_eeg1, sim,  zassenhaus_order=1) #leading order only
            print('computed dem 1')

            generator_infidelity = sum(v**2 for v in eoc_eeg1.values())#H-only model
        
            stimcirc_correct_rounds = stim.Circuit.generated("surface_code:rotated_memory_z", rounds=rounds, distance=d)
            mr_used_qubit_labels = [int(q.split(') ')[1]) for q in str(stimcirc_correct_rounds).split('R ')[0].split('\n')[:-1]]+mr_qubit_labels[stimcirc_correct_rounds.num_qubits:]
            
            qubit_dictionary={}
            for new_lbl,lbl in enumerate(mr_used_qubit_labels):
                qubit_dictionary[lbl]=new_lbl
        
            mr_pcircuit, mr_qubit_labels, mr_ancilla_qubits, data_qubits, ancilla_qubits, x_ancilla_qubits, z_ancilla_qubits, qubit_labels = surface.setup_surface_code(d, rounds)
            qiskit_circ = build_noisy_surface_code_qiskit(mr_pcircuit, mr_used_qubit_labels, qubit_dictionary,unitary_error_dict)
        
            state = Statevector.from_instruction(qiskit_circ)
        
            qargs = [qubit_dictionary[j] for j in mr_ancilla_qubits]+[qubit_dictionary[j] for j in data_qubits[:3]]
            print(qargs)
            qargs.reverse()
            print(qargs)
        
            true_probs_ancilla_readout = state.probabilities_dict(qargs=qargs)
            true_probs_full_readout = compute_logical_z(state, mr_ancilla_qubits, data_qubits, qubit_dictionary)
        
            true_probs_full_readout = {k:v for k,v in true_probs_full_readout.items()}
        
            est_probs = compute_outcome_distribution_from_dem(dem_logical)
    
    
            results_dict = {'dem': dem_logical, 'est_probs':est_probs, 'true_probs': true_probs_full_readout, 'error_dict':error_rates_dict, 'generator_infidelity': generator_infidelity, 'eoc_eeg1': eoc_eeg1, 'erate':erate, 'full_reasout':state.probabilities_dict()}
        
            #dump the results
            with open(f'data/sweep_rounds_{rounds}_infidelity_{erate}_{i}.txt', 'wb+') as f:
                pickle.dump(results_dict, f)
            f.close()
            print(f'finished run {i}')
